# log -----------------------------------------------------------------------
log_format: '%(asctime)s - %(levelname)s - %(message)s'
enable_console_log: True
console_log_level: DEBUG
enable_file_log: False
file_log_level: DEBUG
file_log_path: ./log/operating.log

# connect ----------------------------------------------------------------------
host: localhost
service_port: 2000
traffic_manager_port: 8000
world_reload: False
timeout: 10
fixed_delta_seconds: 0.075 # Designed to have no the effect
vehicle_speed_limit: -50

# camera ----------------------------------------------------------------------
image_size: [ 1152,2048 ]
fov: 90

# processor --------------------------------------------------------------------
city_object_labels: [ 14 ]

# visual_assessment -------------------------------------------------------------------------
visual_assessment_camera_num: 4
visual_assessment_data_retrieval_rate: 60
visual_assessment_save_video: True
visual_assessment_video_fps: 30
visual_assessment_video_path: output/video.mp4

visual_assessment_radius: 8
visual_assessment_height: 5

# dataset_generate ----------------------------------------------------------------------
dataset_path: output
dataset_name: default1
dataset_generate_use_radius: True
dataset_generate_radius: 5
dataset_generate_height: 5
dataset_generate_offset_x: 8
dataset_generate_offset_y: 8
dataset_generate_image_num: 50
dataset_generate_interval: 1 # at least 1
